using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VitaminKitty.Models
{
    public class TwitterConsumer
    {
        /// <summary>
        /// Twitter Developer API key as a string for Vitamin Kitty
        /// </summary>
        [Required()]
        public string ApiKey { get; set; }

        /// <summary>
        /// Twitter Developer API secrete as a string for Vitamin Kitty
        /// </summary>
        [Required()]
        public string ApiSecret { get; set; }

        /// <summary>
        /// Twitter access token. Generated by the user.
        /// </summary>
        [Required()]
        public string AccessToken { get; set; }

        /// <summary>
        /// Twitter access secrete. Generated by the user.
        /// </summary>
        [Required()]
        public string AccessSecret{ get; set; }
    }
}
